### ISSUE TITLE
moduleを自動インストールさせるべき

### ISSUE THREAD

**Issue by equanz** [equanz/calconv#2]

**Comment by raryosu** [comment]
http://www.lifewithpython.com/2014/03/python-install-multiple-modules-.html
この辺を参考に `requirements.txt` を置くと良いかと思います。

**Comment by equanz** [comment]
@raryosu こちらでは調べきれなかったので参考になります。

**Comment by equanz** [comment]
@raryosu 資料を元に修正しました。ありがとうございました。

**Comment by raryosu** [comment]
👏
